-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the members table
CREATE TABLE IF NOT EXISTS public.members (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "fullName" text NOT NULL,
    nickname text,
    birthday date,
    "weddingAnniversary" date,
    email text,
    phone text,
    "qrCodePayload" text,
    "pictureUrl" text,
    ministries text,
    lg text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    promoted_at timestamp with time zone
);

-- Create the first_timers table
CREATE TABLE IF NOT EXISTS public.first_timers (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "fullName" text NOT NULL,
    email text,
    phone text,
    "qrCodePayload" text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the attendance_logs table for members
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id uuid REFERENCES public.members(id) ON DELETE CASCADE,
    member_name text,
    "timestamp" timestamp with time zone NOT NULL,
    type text,
    method text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the attendance_log_1sttimer table for new comers
CREATE TABLE IF NOT EXISTS public.attendance_log_1sttimer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_timer_id uuid NOT NULL,
    first_timer_name text,
    "timestamp" timestamp with time zone NOT NULL,
    type text,
    method text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the event_config table
CREATE TABLE IF NOT EXISTS public.event_config (
    id bigint PRIMARY KEY,
    pre_reg_start_date date,
    event_date date,
    updated_at timestamp with time zone
);
-- Insert the default config row, but do nothing if the row with id=1 already exists.
INSERT INTO public.event_config (id, pre_reg_start_date, event_date, updated_at) VALUES (1, '2024-01-01', '2024-01-07', now()) ON CONFLICT (id) DO NOTHING;

-- Create the user_qrface table for application users
CREATE TABLE IF NOT EXISTS public.user_qrface (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name text NOT NULL,
    username text NOT NULL UNIQUE,
    "password" text NOT NULL,
    "role" text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
